version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
      - run:
          command: yarn start
          background: true
      - run: $(yarn bin)/wait-on http://localhost:3000
      - run: $(yarn bin)/cypress run --record --key=449e87f1-6085-401e-9135-2b4b43ce6f48
    
workflows:
  version: 2
  build:
    jobs:
      - build
